version: 0.2

phases:
  install:
    commands:
      - curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - node -v
      - npm -v
      - cd frontend
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync build/ s3://serverless-webapp-frontend-ireland/ --delete

artifacts:
  files:
    - '**/*'
